# Generated by Django 2.0.3 on 2020-05-09 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinnerplatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small', models.FloatField()),
                ('large', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dinnerplatter_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasta_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastaorders', to='orders.Order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porders', to='orders.Pasta')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzaorders', to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.IntegerField()),
                ('small', models.FloatField()),
                ('large', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Salad_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saladorders', to='orders.Order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saorders', to='orders.Pasta')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small', models.FloatField()),
                ('large', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('ext1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='e1orders', to='orders.Sub_extra')),
                ('ext2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='e2orders', to='orders.Sub_extra')),
                ('ext3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='e3orders', to='orders.Sub_extra')),
                ('ext4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='e4orders', to='orders.Sub_extra')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborders', to='orders.Order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorders', to='orders.Sub')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='pizza_price',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Pizza_type'),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='top1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1orders', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='top2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2orders', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='top3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='t3orders', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='top4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='t4orders', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porders', to='orders.Pizza_type'),
        ),
        migrations.AddField(
            model_name='dinnerplatter_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinnerorders', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='dinnerplatter_order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorders', to='orders.Dinnerplatter'),
        ),
    ]
