# Generated by Django 2.0.3 on 2020-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='small',
            field=models.FloatField(blank=True),
        ),
    ]
