# Generated by Django 2.0.3 on 2020-05-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200509_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_order',
            name='top1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1orders', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='top2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2orders', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='top3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t3orders', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='top4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t4orders', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_order',
            name='ext1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e1orders', to='orders.Sub_extra'),
        ),
        migrations.AlterField(
            model_name='sub_order',
            name='ext2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e2orders', to='orders.Sub_extra'),
        ),
        migrations.AlterField(
            model_name='sub_order',
            name='ext3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e3orders', to='orders.Sub_extra'),
        ),
        migrations.AlterField(
            model_name='sub_order',
            name='ext4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e4orders', to='orders.Sub_extra'),
        ),
    ]
