# Generated by Django 2.0.3 on 2020-05-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200509_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad_order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saorders', to='orders.Salad'),
        ),
    ]
